version: "3"


services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'xtc-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html:cached
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:cached
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled:cached
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2:cached
    environment:
      - _SYSTEM_DEBUG=true
  mysql:
    build: ./bin/mysql
    container_name: 'xtc-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:cached
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql:cached
      - ${MYSQL_CONFIG-./config/mysql/mycustom.cnf}:/etc/mysql/conf.d/custom.cnf:cached
    environment:
      MYSQL_ROOT_PASSWORD: shop
      MYSQL_DATABASE: xtc
      MYSQL_USER: xtc
      MYSQL_PASSWORD: xtc
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'xtc-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions